package com.jaredsburrows.license.testapp.html

import android.os.Bundle
import android.webkit.WebView
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView

/**
 * Shows the HTML report generated by `com.jaredsburrows.license`.
 *
 * The report is copied to `src/main/assets/open_source_licenses.html` by `copyHtmlReportToAssets`,
 * so it is packaged with the app and can be displayed in a [WebView] without any parsing.
 */
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      MaterialTheme {
        MainScreen()
      }
    }
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun MainScreen() {
  var showLicenses by remember { mutableStateOf(false) }

  Scaffold(
    topBar = { TopAppBar(title = { Text("HTML report") }) },
  ) { contentPadding ->
    Column(
      modifier =
        Modifier
          .fillMaxSize()
          .padding(contentPadding)
          .padding(16.dp),
      horizontalAlignment = Alignment.CenterHorizontally,
      verticalArrangement = Arrangement.spacedBy(16.dp, Alignment.CenterVertically),
    ) {
      Text(
        text = "open_source_licenses.html is packaged as an asset and rendered in a WebView.",
        style = MaterialTheme.typography.bodyMedium,
      )
      Button(onClick = { showLicenses = true }) {
        Text("Show open source licenses")
      }
    }
  }

  if (showLicenses) {
    OpenSourceLicensesDialog(onDismiss = { showLicenses = false })
  }
}

@Composable
private fun OpenSourceLicensesDialog(onDismiss: () -> Unit) {
  AlertDialog(
    onDismissRequest = onDismiss,
    title = { Text("Open source licenses") },
    text = {
      AndroidView(
        factory = { context ->
          WebView(context).apply {
            loadUrl("file:///android_asset/open_source_licenses.html")
          }
        },
        modifier = Modifier.fillMaxSize(),
      )
    },
    confirmButton = {
      TextButton(onClick = onDismiss) {
        Text("OK")
      }
    },
  )
}
