package com.jaredsburrows.license.testapp.html

import android.os.Bundle
import android.webkit.WebView
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.viewinterop.AndroidView

/**
 * Shows the HTML report generated by `com.jaredsburrows.license`.
 *
 * The report is copied to `src/main/assets/open_source_licenses.html` by `copyHtmlReportToAssets`,
 * so it is packaged with the app and can be displayed in a [WebView] without any parsing.
 */
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      MaterialTheme {
        MainScreen()
      }
    }
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun MainScreen() {
  Scaffold(
    topBar = { TopAppBar(title = { Text("HTML report") }) },
  ) { contentPadding ->
    AndroidView(
      factory = { context ->
        WebView(context).apply {
          loadUrl(OPEN_SOURCE_LICENSES)
        }
      },
      modifier =
        Modifier
          .fillMaxSize()
          .padding(contentPadding),
    )
  }
}

internal const val OPEN_SOURCE_LICENSES = "file:///android_asset/open_source_licenses.html"
