package com.jaredsburrows.license.testapp.json

import android.content.ActivityNotFoundException
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.dp

/**
 * Renders a custom license screen from the JSON report generated by `com.jaredsburrows.license`.
 *
 * The report is copied to `src/main/assets/open_source_licenses.json` by `copyJsonReportToAssets`.
 * It lists the libraries and the name/URL of their licenses, so a license screen built from it
 * links out to the license text instead of displaying it.
 */
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      MaterialTheme {
        LicensesScreen()
      }
    }
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
internal fun LicensesScreen() {
  val context = LocalContext.current
  val libraries = remember { context.readOpenSourceLibraries() }

  Scaffold(
    topBar = { TopAppBar(title = { Text("JSON report") }) },
  ) { contentPadding ->
    LazyColumn(
      modifier = Modifier.fillMaxSize(),
      contentPadding = contentPadding,
    ) {
      items(libraries) { library ->
        LibraryRow(library, onLicenseClick = { url -> context.openUrl(url) })
        HorizontalDivider()
      }
    }
  }
}

@Composable
private fun LibraryRow(
  library: OpenSourceLibrary,
  onLicenseClick: (String) -> Unit,
) {
  Column(
    modifier =
      Modifier
        .fillMaxWidth()
        .padding(horizontal = 16.dp, vertical = 12.dp),
  ) {
    Text(
      text = library.name,
      style = MaterialTheme.typography.titleMedium,
    )

    if (library.developers.isNotEmpty()) {
      Text(
        text = "Copyright © ${library.developers.joinToString()}",
        style = MaterialTheme.typography.bodySmall,
      )
    }

    if (library.licenses.isEmpty()) {
      Text(
        text = "No license found",
        style = MaterialTheme.typography.bodyMedium,
      )
    } else {
      library.licenses.forEach { license ->
        val name = license.name ?: license.url.orEmpty()
        val url = license.url

        Text(
          text = name,
          style = MaterialTheme.typography.bodyMedium,
          color = MaterialTheme.colorScheme.primary,
          textDecoration = if (url != null) TextDecoration.Underline else null,
          modifier = if (url != null) Modifier.clickable { onLicenseClick(url) } else Modifier,
        )
      }
    }
  }
}

private fun Context.openUrl(url: String) {
  try {
    startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(url)).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK))
  } catch (_: ActivityNotFoundException) {
    // No browser installed, nothing to show.
  }
}
