package com.jaredsburrows.license.testapp.json

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/** One entry of the JSON report generated by `com.jaredsburrows.license`. */
data class OpenSourceLibrary(
  val name: String,
  val version: String?,
  val developers: List<String>,
  val url: String?,
  val licenses: List<OpenSourceLicense>,
)

/** A license of an [OpenSourceLibrary]. */
data class OpenSourceLicense(
  val name: String?,
  val url: String?,
)

/**
 * Read `open_source_licenses.json` out of the assets. The report is copied there by the
 * `copyJsonReportToAssets` option of the plugin.
 */
fun Context.readOpenSourceLibraries(assetName: String = "open_source_licenses.json"): List<OpenSourceLibrary> =
  parseOpenSourceLibraries(assets.open(assetName).bufferedReader().use { it.readText() })

/** Parse the JSON report. */
fun parseOpenSourceLibraries(json: String): List<OpenSourceLibrary> =
  JSONArray(json).mapObjects { library ->
    OpenSourceLibrary(
      name = library.stringOrNull("project") ?: library.stringOrNull("dependency").orEmpty(),
      version = library.stringOrNull("version"),
      developers = library.optJSONArray("developers").toStringList(),
      url = library.stringOrNull("url"),
      licenses =
        library.optJSONArray("licenses").mapObjects { license ->
          OpenSourceLicense(
            name = license.stringOrNull("license"),
            url = license.stringOrNull("license_url"),
          )
        },
    )
  }

/** The report serializes missing values as JSON nulls, which [JSONObject.optString] turns into "null". */
private fun JSONObject.stringOrNull(key: String): String? = if (isNull(key)) null else optString(key).ifEmpty { null }

private fun <T> JSONArray?.mapObjects(transform: (JSONObject) -> T): List<T> =
  if (this == null) emptyList() else (0 until length()).map { transform(getJSONObject(it)) }

private fun JSONArray?.toStringList(): List<String> =
  if (this == null) emptyList() else (0 until length()).map { getString(it) }
