package com.jaredsburrows.license.testapp.fulljson

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp

/**
 * Renders a completely custom license screen from the full JSON report generated by
 * `com.jaredsburrows.license`.
 *
 * The report is copied to `src/main/assets/open_source_licenses.full.json` by
 * `copyJsonFullReportToAssets`. Because it carries the full license text, the app can show the
 * license of a library offline and without a WebView: pick a library, read `license_text`.
 */
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      MaterialTheme {
        LicensesScreen()
      }
    }
  }
}

@Composable
private fun LicensesScreen() {
  val context = LocalContext.current
  val libraries = remember { context.readOpenSourceLibraries() }
  var selected by remember { mutableStateOf<OpenSourceLibrary?>(null) }

  val library = selected
  if (library == null) {
    LibraryListScreen(libraries, onLibraryClick = { selected = it })
  } else {
    BackHandler { selected = null }
    LibraryDetailScreen(library, onBack = { selected = null })
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun LibraryListScreen(
  libraries: List<OpenSourceLibrary>,
  onLibraryClick: (OpenSourceLibrary) -> Unit,
) {
  Scaffold(
    topBar = { TopAppBar(title = { Text("Full JSON report (${libraries.size})") }) },
  ) { contentPadding ->
    LazyColumn(
      modifier = Modifier.fillMaxSize(),
      contentPadding = contentPadding,
    ) {
      items(libraries) { library ->
        Column(
          modifier =
            Modifier
              .fillMaxWidth()
              .clickable { onLibraryClick(library) }
              .padding(horizontal = 16.dp, vertical = 12.dp),
        ) {
          Text(
            text = if (library.version != null) "${library.name} (${library.version})" else library.name,
            style = MaterialTheme.typography.titleMedium,
          )
          Text(
            text = library.licenses.mapNotNull { it.name }.joinToString().ifEmpty { "No license found" },
            style = MaterialTheme.typography.bodyMedium,
          )
        }
        HorizontalDivider()
      }
    }
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun LibraryDetailScreen(
  library: OpenSourceLibrary,
  onBack: () -> Unit,
) {
  Scaffold(
    topBar = {
      TopAppBar(
        title = { Text(library.name) },
        navigationIcon = {
          Text(
            text = "Back",
            style = MaterialTheme.typography.labelLarge,
            color = MaterialTheme.colorScheme.primary,
            modifier =
              Modifier
                .clickable(onClick = onBack)
                .padding(horizontal = 16.dp),
          )
        },
      )
    },
  ) { contentPadding ->
    Column(
      modifier =
        Modifier
          .fillMaxSize()
          .padding(contentPadding)
          .verticalScroll(rememberScrollState())
          .padding(16.dp),
    ) {
      library.dependency?.let {
        Text(text = it, style = MaterialTheme.typography.bodySmall)
      }
      library.developers.takeIf { it.isNotEmpty() }?.let { developers ->
        Text(
          text = "Copyright © ${library.year ?: "20xx"} ${developers.joinToString()}",
          style = MaterialTheme.typography.bodySmall,
        )
      }

      if (library.licenses.isEmpty()) {
        Text(text = "No license found", style = MaterialTheme.typography.bodyMedium)
      }

      library.licenses.forEach { license ->
        Text(
          text = license.name ?: license.url.orEmpty(),
          style = MaterialTheme.typography.titleSmall,
          modifier = Modifier.padding(top = 16.dp),
        )
        Text(
          // Licenses that the plugin does not bundle have no text, only a URL.
          text = license.text ?: license.url ?: "No license text available",
          style = MaterialTheme.typography.bodySmall,
          fontFamily = FontFamily.Monospace,
          modifier = Modifier.padding(top = 8.dp),
        )
      }
    }
  }
}
