package com.jaredsburrows.license.testapp.fulljson

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.BackHandler
import androidx.activity.compose.setContent
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp

/**
 * Renders a completely custom license screen from the full JSON report generated by
 * `com.jaredsburrows.license`.
 *
 * The report is copied to `src/main/assets/open_source_licenses.full.json` by
 * `copyJsonFullReportToAssets`. Because it carries the full license text, the app can show the
 * license of a library offline and without a WebView: pick a library, look its license key up in
 * `license_texts`.
 */
class MainActivity : ComponentActivity() {
  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    setContent {
      MaterialTheme {
        LicensesScreen()
      }
    }
  }
}

@Composable
internal fun LicensesScreen() {
  val context = LocalContext.current
  val report = remember { context.readOpenSourceReport() }
  var selected by remember { mutableStateOf<OpenSourceLibrary?>(null) }

  val library = selected
  if (library == null) {
    LibraryListScreen(report.dependencies, onLibraryClick = { selected = it })
  } else {
    BackHandler { selected = null }
    LibraryDetailScreen(report, library)
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun LibraryListScreen(
  libraries: List<OpenSourceLibrary>,
  onLibraryClick: (OpenSourceLibrary) -> Unit,
) {
  Scaffold(
    topBar = { TopAppBar(title = { Text("Full JSON report") }) },
  ) { contentPadding ->
    LazyColumn(
      modifier = Modifier.fillMaxSize(),
      contentPadding = contentPadding,
    ) {
      items(libraries) { library ->
        Text(
          text = library.name,
          style = MaterialTheme.typography.titleMedium,
          modifier =
            Modifier
              .fillMaxWidth()
              .clickable { onLibraryClick(library) }
              .padding(horizontal = 16.dp, vertical = 16.dp),
        )
        HorizontalDivider()
      }
    }
  }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun LibraryDetailScreen(
  report: OpenSourceReport,
  library: OpenSourceLibrary,
) {
  Scaffold(
    topBar = { TopAppBar(title = { Text(library.name) }) },
  ) { contentPadding ->
    Column(
      modifier =
        Modifier
          .fillMaxSize()
          .padding(contentPadding)
          .verticalScroll(rememberScrollState())
          .padding(16.dp),
    ) {
      if (library.licenses.isEmpty()) {
        Text(text = "No license found", style = MaterialTheme.typography.bodyMedium)
      }

      library.licenses.forEach { license ->
        Text(
          // Licenses that the plugin does not bundle have no text, only a URL.
          text = report.textFor(license) ?: license.url ?: "No license text available",
          style = MaterialTheme.typography.bodySmall,
          fontFamily = FontFamily.Monospace,
          modifier = Modifier.padding(bottom = 16.dp),
        )
      }
    }
  }
}
