package com.jaredsburrows.license.testapp.fulljson

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/**
 * The full JSON report generated by `com.jaredsburrows.license`.
 *
 * Every license text is stored once in [licenseTexts], keyed by license id, and each
 * [OpenSourceLicense] references it by [OpenSourceLicense.key].
 */
data class OpenSourceReport(
  val licenseTexts: Map<String, String>,
  val dependencies: List<OpenSourceLibrary>,
) {
  /** The full text of [license], or null when the plugin does not bundle that license. */
  fun textFor(license: OpenSourceLicense): String? = license.key?.let { licenseTexts[it] }
}

/** One dependency of the full JSON report. */
data class OpenSourceLibrary(
  val name: String,
  val version: String?,
  val developers: List<String>,
  val url: String?,
  val year: String?,
  val dependency: String?,
  val licenses: List<OpenSourceLicense>,
)

/** A license of an [OpenSourceLibrary], as declared by its POM. */
data class OpenSourceLicense(
  val name: String?,
  val url: String?,
  val key: String?,
)

/**
 * Read `open_source_licenses.full.json` out of the assets. The report is copied there by the
 * `copyJsonFullReportToAssets` option of the plugin.
 */
fun Context.readOpenSourceReport(assetName: String = "open_source_licenses.full.json"): OpenSourceReport =
  parseOpenSourceReport(assets.open(assetName).bufferedReader().use { it.readText() })

/** Parse the full JSON report. */
fun parseOpenSourceReport(json: String): OpenSourceReport {
  val report = JSONObject(json)

  val licenseTexts = report.optJSONObject("license_texts") ?: JSONObject()

  return OpenSourceReport(
    licenseTexts = licenseTexts.keys().asSequence().associateWith { licenseTexts.getString(it) },
    dependencies =
      report.optJSONArray("dependencies").mapObjects { library ->
        OpenSourceLibrary(
          name = library.stringOrNull("project") ?: library.stringOrNull("dependency").orEmpty(),
          version = library.stringOrNull("version"),
          developers = library.optJSONArray("developers").toStringList(),
          url = library.stringOrNull("url"),
          year = library.stringOrNull("year"),
          dependency = library.stringOrNull("dependency"),
          licenses =
            library.optJSONArray("licenses").mapObjects { license ->
              OpenSourceLicense(
                name = license.stringOrNull("license"),
                url = license.stringOrNull("license_url"),
                key = license.stringOrNull("license_key"),
              )
            },
        )
      },
  )
}

/** The report serializes missing values as JSON nulls, which [JSONObject.optString] turns into "null". */
private fun JSONObject.stringOrNull(key: String): String? = if (isNull(key)) null else optString(key).ifEmpty { null }

private fun <T> JSONArray?.mapObjects(transform: (JSONObject) -> T): List<T> =
  if (this == null) emptyList() else (0 until length()).map { transform(getJSONObject(it)) }

private fun JSONArray?.toStringList(): List<String> =
  if (this == null) emptyList() else (0 until length()).map { getString(it) }
