package com.jaredsburrows.license.testapp.fulljson

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/** One entry of the full JSON report generated by `com.jaredsburrows.license`. */
data class OpenSourceLibrary(
  val name: String,
  val version: String?,
  val developers: List<String>,
  val url: String?,
  val year: String?,
  val dependency: String?,
  val licenses: List<OpenSourceLicense>,
)

/**
 * A license of an [OpenSourceLibrary]. Unlike the plain JSON report, the full JSON report also
 * carries [text], the complete license text, which is null for licenses the plugin does not bundle.
 */
data class OpenSourceLicense(
  val name: String?,
  val url: String?,
  val text: String?,
)

/**
 * Read `open_source_licenses.full.json` out of the assets. The report is copied there by the
 * `copyJsonFullReportToAssets` option of the plugin.
 */
fun Context.readOpenSourceLibraries(assetName: String = "open_source_licenses.full.json"): List<OpenSourceLibrary> {
  val json = assets.open(assetName).bufferedReader().use { it.readText() }

  return JSONArray(json).mapObjects { library ->
    OpenSourceLibrary(
      name = library.stringOrNull("project") ?: library.stringOrNull("dependency").orEmpty(),
      version = library.stringOrNull("version"),
      developers = library.optJSONArray("developers").toStringList(),
      url = library.stringOrNull("url"),
      year = library.stringOrNull("year"),
      dependency = library.stringOrNull("dependency"),
      licenses =
        library.optJSONArray("licenses").mapObjects { license ->
          OpenSourceLicense(
            name = license.stringOrNull("license"),
            url = license.stringOrNull("license_url"),
            text = license.stringOrNull("license_text"),
          )
        },
    )
  }
}

/** The report serializes missing values as JSON nulls, which [JSONObject.optString] turns into "null". */
private fun JSONObject.stringOrNull(key: String): String? = if (isNull(key)) null else optString(key).ifEmpty { null }

private fun <T> JSONArray?.mapObjects(transform: (JSONObject) -> T): List<T> =
  if (this == null) emptyList() else (0 until length()).map { transform(getJSONObject(it)) }

private fun JSONArray?.toStringList(): List<String> =
  if (this == null) emptyList() else (0 until length()).map { getString(it) }
